if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-3";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(250);
//柱坐标系
pair O,i,j,k;
real x,y,z,r,a,h,H,pz;
path cir,clp;
picture tmp;
O = (0,0);
x = 2;
y = 1.5;
z = 3.3;
i = (-sqrt(2)/4,-sqrt(14)/12);
j = (sqrt(14)/4,-sqrt(2)/12);
k = (0,2*sqrt(2)/3);
draw(Label("$x$",EndPoint),O--x*i,Arrow);
draw(Label("$y$",EndPoint),O--y*j,Arrow);
draw(Label("$z$",EndPoint),O--z*k,Arrow);
r = 1;
h = 2.5;
pair hcir(real t){
return r*cos(t)*i+r*sin(t)*j+H*k;
}
clp = r*i--r*j--h*k--cycle;
unfill(clp);
draw(tmp,Label("$x$",EndPoint),O--x*i,dashed,Arrow);
draw(tmp,Label("$y$",EndPoint),O--y*j,dashed,Arrow);
draw(tmp,Label("$z$",EndPoint),O--z*k,dashed,Arrow);
label(tmp,"$O$",O,W);
clip(tmp,clp);
add(tmp);
erase(tmp);
H = 0;
draw(graph(hcir,-1.2,pi-1.2),linewidth(1bp));
draw(graph(hcir,pi-1.2,2*pi-1.2),dashed);
H = h;
draw(graph(hcir,0,2*pi),linewidth(1bp));
pz = 0.65*h;
H = pz;
draw(graph(hcir,-1.2,pi-1.2),orange);
draw(graph(hcir,pi-1.2,2*pi-1.2),dashed+orange);
draw(r*dir(180)--r*dir(180)+h*k,linewidth(1bp));
draw(r*dir(0)--r*dir(0)+h*k,linewidth(1bp));
pair P,er,et,ez;
real theta;
pair clycoor(real r,real theta,real z){
return r*cos(theta)*i+r*sin(theta)*j+z*k;
}
theta = pi/3;
P = clycoor(r,theta,pz);
draw(O--P-pz*k,dashed+orange);
draw(Label("$z$",MidPoint,Relative(W),black),P-pz*k--P,orange);
draw(Label("$\rho$",MidPoint,Relative(W)),pz*k--P,dashed);
er = clycoor(r,theta,0);
et = clycoor(r,theta+pi/2,0);
ez = clycoor(0,theta,1);
draw(Label("$\boldsymbol{e}_\rho$",EndPoint),P--P+er,red,Arrow);
draw(Label("$\boldsymbol{e}_\phi$",EndPoint),P--P+et,red,Arrow);
draw(Label("$\boldsymbol{e}_z$",EndPoint),P--P+ez,red,Arrow);
dot(P);
r = 0.3;
H = 0;
draw(Label("$\phi$",MidPoint,Relative(E)),graph(hcir,0,theta),Arrow);
