if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-118";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
usepackage("siunitx");
import graph;
import math;
size(200);
//45页5.16受力分析
pair O;
real alpha,phi,P,R,RR,r;
alpha = 30;
phi = 40;
P = 1;
R = P/Sin(45+phi+alpha/2)*Sin(45-alpha/2);
RR = P/Sin(45+alpha/2)*Sin(45-alpha/2);
r = 0.1;
draw(Label("$\boldsymbol{P}$",EndPoint,Relative(E)),O--P*dir(-90),Arrow);
draw(Label("$\boldsymbol{R}$",EndPoint,Relative(E)),P*dir(-90)--P*dir(-90)+R*dir(90-alpha-phi),Arrow);
draw(Label("$\boldsymbol{T}$",Relative(0.7),Relative(E)),P*dir(-90)+R*dir(90-alpha-phi)--O,Arrow);
draw(P*dir(-90)--P*dir(-90)+RR*dir(90-alpha),dashed);
draw(Label("$\phi$",MidPoint,Relative(E)),arc(P*dir(-90),r,90-alpha-phi,90-alpha),Arrows);
draw(Label("$\alpha$",MidPoint,Relative(E)),arc(P*dir(-90),r,90-alpha,90),Arrows);
draw(P*dir(-90)--interp(P*dir(-90)+R*dir(90-alpha-phi),O,0.2),dashed,Arrow);
draw(O--R*Sin(alpha+phi)*dir(0),dashed);
draw(Label("$\dfrac{\pi}{4}+\dfrac{\alpha}{2}$",MidPoint,Relative(E)),arc(O,r,-45-alpha/2,0),Arrows);
