if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-82";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(250);
//角速度的方向与角动量的方向
pair O,a,b,L,omega;
real rx,ry,theta,lL,lomega;
path rect,cir;
picture tmp1,tmp2;
O = (0,0);
a = (2,0);
b = (0.7,0.8);
L = (0,-0.9);
omega = L+0.7*dir(190);
lL = 2.2;
lomega = lL/cos((degrees(omega)-degrees(L))*pi/180);
rx = 1.5;
ry = 1;
theta = 50;
rect = L+a+b--L+a-b--L-a-b--L-a+b--cycle;
cir = rotate(theta)*xscale(rx)*yscale(ry)*unitcircle;
dot(O);
label("$O$",O,N);
draw(cir);
draw(tmp1,rect);
unfill(tmp1,cir);
add(tmp1);
erase(tmp1);
draw(tmp1,O--lL*L,blue+dashed,Arrow);
draw(tmp1,O--lomega*omega,red+dashed,Arrow);
add(tmp2,tmp1);
clip(tmp1,rect);
add(tmp1);
clip(tmp2,cir);
unfill(tmp2,rect);
add(tmp2);
erase(tmp1);
erase(tmp2);
draw(tmp1,O--lL*dir(L),blue,Arrow);
draw(tmp1,Label("$\boldsymbol{\omega}$",EndPoint,S,black),O--lomega*dir(omega),red,Arrow);
label(tmp1,"$\boldsymbol{L}$（常矢量）",lL*dir(L)+(0.6,0),S);
unfill(tmp1,rect);
unfill(tmp1,cir);
add(tmp1);
erase(tmp1);
dot(omega);
dot(L);
label("$N$",omega,N);
label("$L$",L,NE);
draw(L--omega,dashed);
