if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-98";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(200);
//理论力学：30页1.13
pair O,a,b,m,M;
real r;
O = (0,0);
a = (1.5,0);
b = 0.8*dir(60);
m = dir(30);
M = (0,-1.5);
r = 0.05;
draw((O+a+b)--(O-a+b)--(O-a-b)--(O+a-b)--cycle);
draw(O--0.6*a,dashed);
draw(Label("$r$",MidPoint,Relative(W)),O--m);
draw(O--(0,-b.y),dashed);
draw((0,-b.y)--M);
draw(Label("$z$",EndPoint),O--(0,1),Arrow);
fill(shift(m)*scale(r)*unitcircle,black);
label("$m$",m,E);
fill(shift(M)*scale(r)*unitcircle,black);
label("$M$",M,W);
label("$\theta$",0.5*dir(15));
unfill(scale(r)*unitcircle);
draw(scale(r)*unitcircle);
label("$O$",O,W);
