if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-123";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
usepackage("siunitx");
import graph;
import math;
size(250);
//57页6.21
pair O,i,j,k;
real l,L,x,y,z,d1,d2;
O = (0,0);
i = (-sqrt(2)/4,-sqrt(14)/12);
j = (sqrt(14)/4,-sqrt(2)/12);
k = (0,2*sqrt(2)/3);
l = 1;
L = 0.82;
x = (l-sqrt(3*L**2-2*l**2))/3;
y = x;
z = x;
d1 = 0.1;
d2 = 0.08;
draw(Label("$x$",EndPoint),O--1.4*i,Arrow);
draw(Label("$y$",EndPoint),O--1.4*j,Arrow);
draw(Label("$z$",EndPoint),O--1.4*k,Arrow);
label("$O$",O,W);
draw(i--x*i+y*j+z*k--k,linewidth(0.8bp));
draw(x*i+y*j+z*k--j,linewidth(0.8bp));
draw(x*i+y*j+z*k--x*i+y*j+z*k-0.5*l*k);
unfill(box(x*i+y*j+z*k-0.5*l*k-(d1,d2),x*i+y*j+z*k-0.5*l*k+(d1,d2)));
draw(box(x*i+y*j+z*k-0.5*l*k-(d1,d2),x*i+y*j+z*k-0.5*l*k+(d1,d2)));
label("$Q$",x*i+y*j+z*k-0.5*l*k);
label("$A$",i,E);
label("$B$",j,NE);
label("$C$",k,E);
label("$D$",x*i+y*j+z*k,NE);
label("$E$",x*i+y*j+z*k-0.5*l*k+d2*k,NE);
dot(i,UnFill);
dot(j,UnFill);
dot(k,UnFill);
dot(x*i+y*j+z*k,UnFill);
