if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-65";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(250);
//刚体的运动
pair O,OO,r,i,j,k;
picture tmp;
O = (0,0);
i = 0.5*dir(-135);
j = dir(0);
k = dir(90);
draw(Label("$X_0$",EndPoint),O--i,Arrow);
draw(Label("$Y_0$",EndPoint),O--j,Arrow);
draw(Label("$Z_0$",EndPoint),O--k,Arrow);
label("$O_0$",O,SSE);
OO = (0.7,0.5);
draw(tmp,Label("$X$",EndPoint,SE),O--i,Arrow);
draw(tmp,Label("$Y$",EndPoint),O--j,Arrow);
draw(tmp,Label("$Z$",EndPoint),O--k,Arrow);
label(tmp,"$O$",O,SSE);
add(shift(OO)*scale(0.9)*tmp);
erase(tmp);
real f(real x){
return x**2-0.3;
}
draw(tmp,graph(f,-1.5,1.5),linewidth(1bp));
draw(tmp,shift((0,f(1.5)))*yscale(1/3)*scale(1.5)*unitcircle,linewidth(1bp));
add(shift(OO)*rotate(-25)*scale(0.4)*tmp);
erase(tmp);
draw(tmp,Label("$x$",EndPoint,S),rotate(-25)*(O--i),Arrow);
draw(tmp,Label("$y$",EndPoint),rotate(-25)*(O--j),Arrow);
draw(tmp,Label("$z$",EndPoint,W),rotate(-25)*(O--k),Arrow);
add(shift(OO)*scale(0.9)*tmp);
r = (-0.1,0.6);
//dot(OO+r);
draw(Label("$\boldsymbol{r}_O$",Relative(0.3),Relative(E),black),O--OO,red,Arrow);
draw(Label("$\boldsymbol{r}'$",Relative(0.3),Relative(W),black),OO--OO+r,red,Arrow);
draw(Label("$\boldsymbol{r}$",Relative(0.5),Relative(W),black),O--OO+r,red,Arrow);
//draw(O--(1.8,1.55),invisible);
