if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-129";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
usepackage("siunitx");
import graph;
import math;
size(250);
//106页15.6
picture dashpic,tmp;
pair O,A,B,dash,P;
real alpha,phi,a,b,l,d,d1,d2,r,r0,dl1,dl2;
path tre;
O = (0,0);
alpha = 50;
a = 2;
l = 3;
b = sqrt(l**2-(a*Sin(alpha))**2)-a*Cos(alpha);
phi = aSin(a/l*Sin(alpha));
A = a*dir(180-alpha);
B = b*dir(0);
draw(Label("$x$",EndPoint,Relative(E)),(1.5*A.x,0)--2.3*B);
draw(Label("$y$",EndPoint,Relative(E)),O--(0,1.5*A.y));
draw(1.5*A--O--2*B,linewidth(1bp));
d = 0.07;
d1 = 0.2;
d2 = 0.1;
r = d;
unfill(shift(A)*rotate(180-alpha)*box((-d1,-d2),(d1,d2)));
draw(shift(A)*rotate(180-alpha)*box((-d1,-d2),(d1,d2)),linewidth(0.8bp));
unfill(shift(B)*box((-d1,-d2),(d1,d2)));
draw(shift(B)*box((-d1,-d2),(d1,d2)),linewidth(0.8bp));
unfill(shift(B)*rotate(-phi)*box((-l,-d),(0,d)));
draw(shift(B)*rotate(-phi)*box((-l,-d),(0,d)),linewidth(0.8bp));
unfill(shift(A)*scale(r)*unitcircle);
draw(shift(A)*scale(r)*unitcircle,linewidth(0.8bp));
unfill(shift(B)*scale(r)*unitcircle);
draw(shift(B)*scale(r)*unitcircle,linewidth(0.8bp));
draw(A--interp(A,B,1.2),dashed);
r0 = 0.4;
draw(Label("$\phi$",MidPoint,Relative(W)),arc(B,r0,0,-phi),Arrows);
r0 = 0.8;
draw(Label("$\alpha$",MidPoint,Relative(E)),arc(O,r0,180-alpha,180),Arrows);

dl2 = 0.18;
dash = dl2*dir(-135);
tre = O--l*dir(0);
//draw(dashpic,tre,linewidth(1bp));
for(real rp=0;rp<=1;rp=rp+0.02){
P = relpoint(tre,rp);
draw(dashpic,P--P+dash);
}
dl1 = 0.4*b;
add(tmp,dashpic);
clip(tmp,box((0,1),(dl1,-dl2)));
add(shift(2*B-dl1*dir(0))*tmp);
dl1 = 0.25*a;
clip(tmp,box((0,1),(dl1,-dl2)));
add(shift(1.5*A)*rotate(-alpha)*tmp);
erase(tmp);
erase(dashpic);
tre = r0*dir(A)--O--r0*dir(B);
for(real rp=0;rp<=1;rp=rp+0.04){
P = relpoint(tre,rp);
draw(dashpic,P--P+dash);
}
clip(dashpic,box(0.6*r0*dir(A)+2*dl2*dir(180),0.7*r0*dir(B)+dl2*dir(-90)));
add(dashpic);
label("$O$",O,2*S);
label("$A$",A,2*NNE);
label("$B$",B,2*NNE);
