if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-126";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
usepackage("siunitx");
import graph;
import math;
size(250);
//91页12.31
picture dashpic;
pair O,A,M,dash,P;
real phi,a,b,l1,l2,d,dd,r,tri;
path tre;
O = (0,0);
phi = 60;
a = 1;
b = 0.8;
l1 = a/Cos(phi);
l2 = 1.1;
d = 0.05;
dd = 1.5*d;
r = 0.04;
dash = dir(-135);
tre = a*dir(90)--a*dir(-90);
draw(dashpic,tre,linewidth(1bp));
for(real r=0;r<=1;r=r+0.02){
P = relpoint(tre,r);
draw(dashpic,P--P+dash);
}
draw(Label("$x$",EndPoint),O--1.5*a*dir(0),Arrow);
draw(Label("$D$",BeginPoint,Relative(W)),a*dir(0)+a*dir(-90)--a*dir(0)+1.3*l1*dir(90));
label("$C$",a*dir(0)+1.3*l1*dir(90),W);
draw(rotate(phi)*box((-l2,-d),(l1,d)),linewidth(0.8bp));
draw(Label("$B$",EndPoint),l1*dir(phi)--1.05*l2*dir(phi-180),dashed);
draw(O--0.4*a*dir(-90));
M = (l1-b)*dir(phi);
A = l1*dir(phi);
draw(M--M+0.4*a*dir(phi+90));
draw(A--A+0.4*a*dir(phi+90));
draw(Label("$\boldsymbol{v}_A$",EndPoint,Relative(E)),A--A+0.5*dir(90),Arrow);
tri = 0.23;
draw(O--tri*dir(180-30)--tri*dir(180+30)--cycle,linewidth(0.8bp));
clip(dashpic,box((-2*d,-tri),(1,tri)));
add(shift(tri*Sin(60)*dir(180))*dashpic);
unfill(rotate(phi)*box((-1.8*dd,-dd),(1.8*dd,dd)));
draw(rotate(phi)*box((-1.8*dd,-dd),(1.8*dd,dd)),linewidth(0.8bp));
draw(shift(O)*scale(r)*unitcircle,linewidth(0.8bp));
unfill(shift(A)*rotate(90)*box((-1.8*dd,-dd),(1.8*dd,dd)));
draw(shift(A)*rotate(90)*box((-1.8*dd,-dd),(1.8*dd,dd)),linewidth(0.8bp));
draw(shift(A)*scale(r)*unitcircle,linewidth(0.8bp));
draw(Label("$a$",MidPoint,Relative(E)),0.3*a*dir(-90)--a*dir(0)+0.3*a*dir(-90),Arrows);
draw(Label("$b$",MidPoint,Relative(W)),M+0.3*a*dir(phi+90)--A+0.3*a*dir(phi+90),Arrows);
label("$A$",A,2*E);
dot(M);
label("$M$",M,SE);
label("$O$",O,2.5*dir(110));
r = 0.4;
draw(Label("$\phi$",MidPoint,Relative(E)),arc(O,r,0,phi),Arrow);
