if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-24";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(200);
//第二章例1图
pair O,x,y;
real h,r,x0;
O = (0,0);
x = (1,0);
y = (0,0.5);
h = 1.7;
r = 0.8;
x0 = 0.6;
draw(Label("$x$",EndPoint),-x--x,Arrow);
draw(Label("$y$",EndPoint),(0,-h)--y,Arrow);
draw(O--(r,-h)--(-r,-h)--cycle);
label("$\alpha$",(0,-0.25*h),E);
draw(interp(O,(-r,-h),x0)--interp(O,(r,-h),x0),red+linewidth(1bp));
label("$x_0$",(0,-x0*h),SE);
//draw(O--x+(0.3,0),invisible);
