if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-68";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
usepackage("amssymb");
size(300);
import graph;
import math;
//定轴转动公式
real r,theta,a,h;
r = 1;
a = 0.5;
theta = 20;
h = 3;
path p;
p = rotate(-theta)*shift((0,h))*scale(r)*yscale(a)*unitcircle;
draw(p,linewidth(0.8bp));
draw(Label("$N$",EndPoint,Relative(W)),(0,0)--h*dir(90-theta),Arrow);
draw(h*dir(90-theta)--(h+1)*dir(90-theta));
draw(Label("$\boldsymbol{n}$",EndPoint,Relative(W)),(0,0)--dir(90-theta),Arrow);
label("$(\boldsymbol{n}\cdot\boldsymbol{r})\boldsymbol{n}$",0.6*h*dir(90-theta),dir(180-theta));
pair NP,P,Q;
NP = h*dir(90-theta);
P = relpoint(p,0);
Q = relpoint(p,0.9);
draw(Label("$P$",EndPoint),NP--P,Arrow);
draw(Label("$Q$",EndPoint),NP--Q,Arrow);
draw(Label("$\boldsymbol{r}$",Relative(0.7),Relative(E)),(0,0)--P,Arrow);
draw(Label("$\boldsymbol{r}'$",Relative(0.7),Relative(W)),(0,0)--Q,Arrow);
real R = 0.3;
draw(Label("$\phi$",MidPoint,Relative(W)),arc(NP,R,degrees(P-NP),degrees(Q-NP)),Arrow);
draw(Label("$V$",BeginPoint),NP+0.7*(P-NP)--Q,Arrow);
picture pic;
r = 1.3;
path q;
q = scale(r)*unitcircle;
pair P,Q;
draw(pic,q,linewidth(0.8bp));
P = relpoint(q,0);
Q = relpoint(q,0.86);
draw(pic,Label("$P$",EndPoint),(0,0)--P,Arrow);
draw(pic,Label("$Q$",EndPoint),(0,0)--Q,Arrow);
draw(pic,Label("$\boldsymbol{r}\times\boldsymbol{n}$",MidPoint,Relative(E)),(0,0)--r*dir(-90),Arrow);
draw(pic,Label("$\phi$",MidPoint,Relative(W)),arc((0,0),R,0,degrees(Q)-360),Arrow);
draw(pic,Label("$V$",BeginPoint),(Q.x,0)--Q,Arrow);
label(pic,"$N$",(0,0),NW);
add(shift((2.6+r,r+0.5))*pic);
