if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-125";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
usepackage("siunitx");
import graph;
import math;
size(200);
//91页12.19
picture tmp;
pair O,C,M;
real phi,r,ro,ri;
C = (0,0);
phi = 55;
r = 1;
ri = 0.02;
ro = 0.04;
O = r*dir(180);
M = r*dir(phi);
draw(scale(r)*unitcircle,linewidth(0.8bp));
draw(O--O+0.5*dir(90));
draw(Label("$A$",EndPoint),O--interp(O,M,1.3),linewidth(0.8bp));
unfill(shift(O)*scale(ro)*unitcircle);
draw(shift(O)*scale(ri)*unitcircle,linewidth(0.8bp));
draw(shift(O)*scale(ro)*unitcircle,linewidth(0.8bp));
unfill(shift(M)*scale(ro)*unitcircle);
draw(shift(M)*scale(ro)*unitcircle,linewidth(0.8bp));
draw(tmp,arc(C,r,0,phi),linewidth(0.8bp));
clip(tmp,shift(M)*scale(ro)*unitcircle);
add(tmp);
label("$O$",O,W);
label("$M$",M,2*N);
draw(Label("$\phi$",Relative(0.7),Relative(W)),arc(O,9*ro,90,degrees(M-O)),Arrow);
draw(O--C--M,dashed);
draw(Label("$2\phi$",MidPoint,Relative(E)),arc(C,3*ro,phi,180),Arrows);
