if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-54";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(300);
//阶跃中心势散射
pair O;
real r,alpha,beta,theta,n,l,r0;
r = 1;
alpha = 30;
beta = 55;
n = 1.8;
l = 1;
theta = 2*beta-2*alpha;
draw(scale(r)*unitcircle);
draw(O--n*r*dir(180-alpha),dashed);
draw(O--n*r*dir(2*beta-alpha),dashed);
draw(r*dir(180-alpha)+l*dir(180)--r*dir(180-alpha),red,Arrow);
draw(r*dir(180-alpha)--r*dir(2*beta-alpha),red,Arrow);
draw(r*dir(2*beta-alpha)--r*dir(2*beta-alpha)+l*dir(theta),red,Arrow);
draw(O--n*r*dir(theta),dashed);
draw(n*r*dir(180)--n*r*dir(0),dashed);
draw(Label("$b$",MidPoint,E),r*dir(180-alpha)--((r*dir(180-alpha)).x,0),Arrows);
draw(Label("$r_{\mathrm{min}}$",Relative(0.6),Relative(E)),O--interp(r*dir(180-alpha),r*dir(2*beta-alpha),0.5),Arrows);
r0 = 0.2;
draw(Label("$\alpha$",MidPoint,Relative(W)),arc(r*dir(180-alpha),r0,180,180-alpha),Arrow);
draw(Label("$\beta$",MidPoint,Relative(W)),arc(r*dir(180-alpha),r0,beta-alpha,-alpha),Arrow);
draw(Label("$\theta$",MidPoint,Relative(E)),arc(O,r0,0,theta),Arrow);
