if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-94";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

usepackage("xeCJK");
usepackage("amsmath");
import graph;
import math;
size(200);
//重力引力离心力2
pair O;
real rr,lambda,F,Ft;
O = (0,0);
lambda = 50;
F = 0.7;
Ft = 0.2;
draw(Label("$\boldsymbol{F}$",Relative(0.6),Relative(E)),F*dir(lambda)--O,Arrow);
draw(Label("$\boldsymbol{F}_t$",MidPoint,Relative(E)),O--Ft*dir(0),Arrow);
draw(Label("$m\boldsymbol{g}$",MidPoint,Relative(W)),F*dir(lambda)--Ft*dir(0),Arrow);
draw(O--(0,F*dir(lambda).y)--F*dir(lambda),dashed);
draw(Ft*dir(0)--Ft*dir(0)+(0,F*dir(lambda).y),dashed);
draw(Ft*dir(0)--Ft*dir(0)+Ft*Sin(lambda)*dir(90+lambda),dashed);
rr = 0.05;
draw(Label("$\lambda$",MidPoint,Relative(E)),arc(O,rr,0,lambda),Arrow);
rr = 0.1;
draw(Label("$\alpha$",MidPoint,Relative(E)),arc(F*dir(lambda),rr,180+lambda,degrees(Ft*dir(0)-F*dir(lambda))),Arrow);
draw(O--F*dir(lambda)+(0,0.005),invisible);
