if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-4";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
size(180);
//动点的轨迹
pair O,A[],Os,P,P1,tP,tP1;
O = (0,0);
A[1] = (-2.5,1.5);
A[2] = (-2,2);
A[3] = (-1,2.5);
A[4] = (1,2.5);
A[5] = (2,1);
A[6] = (1,1);
A[7] = (1,2);
A[8] = (3,3);
path tra;
tra = A[1]..A[2]..A[3]..A[4]..A[5]..A[6]..A[7]..A[8];
draw(tra,Arrow(Relative(0.8)));
Os = relpoint(tra,0.05);
P = relpoint(tra,0.15);
tP = 0.8*reldir(tra,0.15);
P1 = relpoint(tra,0.30);
tP1 = 0.8*reldir(tra,0.30);
dot(O);
label("$O$",O,S);
dot(Os);
label("$O_s$",Os,NW);
dot(P);
label("$P$",P,N);
dot(P1);
label("$P_1$",P1,N);
draw(Label("$\boldsymbol{r}$",MidPoint,Relative(W)),O--P,Arrow);
draw(Label("$\boldsymbol{r}_1$",MidPoint,Relative(E)),O--P1,Arrow);
draw(Label("$\Delta \boldsymbol{r}$",MidPoint,Relative(E)),P--P1,Arrow);
label("$s$",relpoint(tra,0.1),S);
draw(Label("$\boldsymbol{\tau}$",EndPoint),P--P+tP,red,Arrow);
draw(Label("$\boldsymbol{\tau}_1$",EndPoint,Relative(W)),P1--P1+tP1,red,Arrow);
