if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-78";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
usepackage("amssymb");
size(200);
import graph;
import math;
//空间极锥与本体极锥情形1
picture tmp;
pair O,i,j,k;
real r,r1,r2,h,h1,h2,theta,alpha,pos,L;
O = (0,0);
i = (-sqrt(2)/4,-sqrt(14)/12);
j = (sqrt(14)/4,-sqrt(2)/12);
k = (0,2*sqrt(2)/3);
pos = 1.88;
r1 = 0.5;
r2 = 0.8;
h1 = 1.6;
h2 = sqrt(r1*r1+h1*h1-r2*r2);
L = 2;
pair cir(real theta){
return r*cos(theta)*i+r*sin(theta)*j+h*k;
}
r = r1;
h = h1;
draw(graph(cir,0,2*pi),blue+dashed);
draw(O--cir(pos),blue+dashed);
draw(xscale(-1)*(O--cir(pos)),blue+dashed);
theta = 90-degrees(cir(pos));
r = r2;
h = h2;
pos = 1.80;
draw(tmp,graph(cir,0,2*pi),red+dashed);
draw(tmp,O--cir(pos),red+dashed);
draw(tmp,xscale(-1)*(O--cir(pos)),red+dashed);
alpha = 90-degrees(cir(pos));
add(rotate(alpha+theta)*tmp);
draw(Label("$\boldsymbol{L}$",EndPoint,black),O--L*dir(90),blue,Arrow);
draw(Label("$\boldsymbol{e}_3$",EndPoint),O--L*dir(90+alpha+theta),Arrow);
//画角速度
real omega,phi,psi,ralpha,rtheta,r0;
ralpha = alpha*pi/180;
rtheta = theta*pi/180;
omega = 1;
phi = sin(ralpha)/sin(ralpha+rtheta)*omega;
psi = sin(rtheta)/sin(ralpha+rtheta)*omega;
draw(Label("$\boldsymbol{\omega}$",EndPoint,Relative(W),black),O--omega*dir(90+theta),red,Arrow);
draw(Label("$\dot{\phi}$",EndPoint,Relative(E),black),O--phi*dir(90),red,Arrow);
draw(Label("$\dot{\psi}$",EndPoint,Relative(W),black),O--psi*dir(90+alpha+theta),red,Arrow);
draw(psi*dir(90+alpha+theta)--omega*dir(90+theta)--phi*dir(90),dashed);
r0 = 0.3;
draw(Label("$\alpha$",MidPoint,Relative(E)),arc(O,r0,90+theta,90+alpha+theta),Arrow);
r0 = 0.3;
draw(Label("$\theta$",MidPoint,Relative(E)),arc(O,r0,90,90+theta),Arrow);
