if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-21";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(200);
//刚性联结的两质点约束
pair O,P1,P2;
O = (0,0);
P1 = (0,1.5);
P2 = (0.8,1);
label("$O$",O,W);
dot(P1);
dot(P2);
label("$P_1$",P1,N);
label("$P_2$",P2,N);
draw(Label("$\boldsymbol{r}_1$",MidPoint,Relative(W)),O--P1,Arrow);
draw(Label("$\boldsymbol{r}_2$",MidPoint,Relative(E)),O--P2,Arrow);
draw(Label("$\boldsymbol{r}$",MidPoint,Relative(W)),P2--P1,Arrow);
draw(Label("$\boldsymbol{R}_1$",EndPoint),P1--interp(P1,P2,-0.6),Arrow);
draw(Label("$\boldsymbol{R}_2$",EndPoint),P2--interp(P2,P1,-0.6),Arrow);
