if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-47";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(250);
//圆心角的几何意义
real x,a,b,c,theta,r;
a = 2;
b = 1.6;
x = 2.5;
c = sqrt(a^2-b^2);
draw((-x,0)--(x,0));
draw((0,-x)--(0,x));
draw(xscale(a)*yscale(b)*unitcircle,linewidth(0.8bp));
draw(scale(a)*unitcircle);
dot((c,0));
theta = 30;
draw((0,0)--a*dir(theta));
pair P;
P = intersectionpoint(xscale(a)*yscale(b)*unitcircle,a*dir(theta)--(a*dir(theta).x,0));
draw((c,0)--P);
draw(a*dir(theta)--(a*dir(theta).x,0));
label("$p$",(P+(a*dir(theta).x,0))/2,E);
r = 0.3;
draw(Label("$\xi$",MidPoint,Relative(E)),arc((0,0),r,0,theta));
r = 0.15;
draw(Label("$\theta$",MidPoint,Relative(E)),arc((c,0),r,0,degrees(P-(c,0))));
label("$a$",(a,0),SE);
label("$b$",(0,b),SW);
label("$ae$",(c,0),S);
