if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-127";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
usepackage("siunitx");
import graph;
import math;
size(300);
//100页14.8
picture ell,tmp,dashpic;
pair O,O1,O2,C,M,dash,P;
real phi,theta,a,b,c,e,l,p,r1,tri,ri,ro,d;
path tre;
O = (0,0);
phi = 35;
a = 3;
b = 1.5;
c = sqrt(a**2-b**2);
e = c/a;
p = b**2/a;
l = 2*a;
tri = 0.3;
ri = 0.05;
ro = 0.1;
d = 0.112;
dash = dir(-135);
tre = a*dir(180)--a*dir(0);
draw(dashpic,tre,linewidth(1.5bp));
for(real r=0;r<=1;r=r+0.015){
P = relpoint(tre,r);
draw(dashpic,P--P+dash);
}
O1 = (-c,0);
draw(tmp,O--tri*dir(-60)--tri*dir(-120)--cycle,linewidth(0.8bp));
clip(dashpic,box((-tri,-d),(tri,1)));
add(tmp,shift(tri*Sin(60)*dir(-90))*dashpic);
add(shift(O1)*rotate(180)*tmp);
draw(ell,xscale(a)*yscale(b)*unitcircle,linewidth(0.8bp));
draw(ell,1.1*a*dir(180)--1.1*a*dir(0),dashed);
add(rotate(phi,O1)*ell);
r1 = p/(1-e*Cos(phi));
M = O1+r1*dir(0);
C = O1+2c*dir(phi);
draw(O1--M--C,dashed);
unfill(shift(O1)*scale(ro)*unitcircle);
draw(shift(O1)*scale(ro)*unitcircle,linewidth(0.8bp));
draw(shift(O1)*scale(ri)*unitcircle,linewidth(0.8bp));
unfill(shift(C)*scale(ri)*unitcircle);
draw(shift(C)*scale(ri)*unitcircle,linewidth(0.8bp));
draw(Label("$\omega_1$",MidPoint,Relative(W)),arc(O1,10*ro,85,phi+5),Arrow);
draw(Label("$\phi$",MidPoint,Relative(W)),arc(O1,10*ro,phi,0),Arrows);
label("$r_1$",O1+0.5*r1*dir(0),S);
label("$I$",O1+c*dir(phi),dir(phi+90));
label("$N_1$",O1+(1.1*a-c)*dir(phi-180),dir(phi-180));
label("$M_1$",O1+(1.1*a+c)*dir(phi),dir(phi));
label("$O_1$",O1,SE);
label("$O'_1$",C,WNW);
O2 = O1+(l,0);
theta = aCos((1-p/(l-r1))/e);
C = O2+2*c*dir(theta-180);
add(shift(O2)*tmp);
add(rotate(theta,O2)*shift((l-2*c)*dir(0))*ell);
draw(O2--M--C,dashed);
unfill(shift(O2)*scale(ro)*unitcircle);
draw(shift(O2)*scale(ro)*unitcircle,linewidth(0.8bp));
draw(shift(O2)*scale(ri)*unitcircle,linewidth(0.8bp));
unfill(shift(C)*scale(ri)*unitcircle);
draw(shift(C)*scale(ri)*unitcircle,linewidth(0.8bp));
unfill(shift(M)*scale(ri)*unitcircle);
draw(shift(M)*scale(ri)*unitcircle,linewidth(0.8bp));
draw(Label("$\omega_2$",EndPoint),arc(O2,10*ro,180-15,180+theta+5),Arrow);
label("$M$",M,SE);
label("$r_2$",O2+0.5*(l-r1)*dir(180),N);
label("$II$",O2+c*dir(theta-180),dir(theta-90));
label("$N_2$",O2+(1.1*a+c)*dir(theta-180),dir(theta-180));
label("$M_2$",O2+(1.1*a-c)*dir(theta),dir(theta));
label("$O_2$",O2,NW);
label("$O'_2$",C,ESE);
