if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-15";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(300);
//第一章例10图
pair O;
real r,l1,l2,hand,a,T;
O = (0,0);
r = 1;
l1 = 4;
l2 = 6;
T = 3;
hand = 2;
a = 0.6;
draw(scale(r)*unitcircle);
draw(O--(0,hand),linewidth(3bp));
draw((-r,0)--(-r,-l1));
draw((-r,0)--(-r-2*a,0));
draw((-r,-l1)--(-r-2*a,-l1));
draw(Label("$X$",MidPoint,W),(-r-1.5*a,0)--(-r-1.5*a,-l1),Arrows);
fill(box((-r-a,-l1-a),(-r+a,-l1+a)),red);
dot((-r,-l1));
draw(Label("$T$",EndPoint,E),(-r,-l1)--(-r,-l1)+dir(90),Arrow);
draw(Label("$Mg$",EndPoint,E),(-r,-l1)--(-r,-l1)+dir(-90),Arrow);
draw((r,0)--(r,-l2+0.1));
draw((r,-T)--(r,-l2+0.1)..(r+0.1,-l2)--(r+3*a,-l2),blue+linewidth(3bp));
dot((r,-(T+l2)/2));
draw(Label("$\rho gx$",EndPoint,W),(r,-(T+l2)/2)--(r,-(T+l2)/2)+dir(-90),Arrow);
draw(Label("$T$",EndPoint,E),(r,-T)--(r,-T)+dir(90),Arrow);
draw((r,-T)--(r+2*a,-T));
draw((r,-l2)--(r+2*a,-l2));
draw(Label("$x$",MidPoint,E),(r+1.5*a,-T)--(r+1.5*a,-l2),Arrows);
//draw(O--(1.5,0),invisible);
