if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-49";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(300);
//质心坐标系中的散射
pair O,O1;
real theta,v1,v2,v;
O = (0,0);
v1 = 2;
v2 = 1;
theta = 40;
draw(Label("$\boldsymbol{v}'_{1i}$",EndPoint,black),O--v1*dir(0),red,Arrow);
draw(Label("$\boldsymbol{v}'_{1f}$",EndPoint,black),O--v1*dir(theta),red,Arrow);
draw(Label("$\boldsymbol{v}'_{2i}$",EndPoint,black),O--v2*dir(180),blue,Arrow);
draw(Label("$\boldsymbol{v}'_{2f}$",EndPoint,black),O--v2*dir(180+theta),blue,Arrow);
draw(arc(O,v1,0,theta),dashed);
draw(arc(O,v2,180,180+theta),dashed);
label("$\theta$",O,5*dir(theta/2));
picture tmp;
O1 = (3.3,-0.3);
v = 2.5;
draw(tmp,Label("$\boldsymbol{v}'_i$",EndPoint,black),O--v*dir(0),Arrow);
draw(tmp,Label("$\boldsymbol{v}'_f$",EndPoint,black),O--v*dir(theta),Arrow);
draw(tmp,arc(O,v,0,theta),dashed);
label(tmp,"$\theta$",O,5*dir(theta/2));
add(shift(O1)*tmp);
//draw((0,0)--(6.7,0),invisible);
