if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-12";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(200);
//第一章例7图
pair O;
real R,r,rr,theta,alpha,dalpha;
O = (0,0);
R = 1;
r = 1.05;
rr = 0.3;
theta = 30;
alpha = 40;
dalpha = 15;
draw(arc(O,R,0,180)--cycle);
draw(arc(O,r,0,180)--cycle);
draw(Label("$R$",MidPoint),O--r*dir(180-theta));
draw(Label("$\theta$",MidPoint,Relative(E)),arc(O,rr*R,180-theta,180),Arrow);
draw(O--r*dir(alpha));
draw(Label("$\alpha$",MidPoint,Relative(E)),arc(O,rr*R,0,alpha),Arrow);
draw(O--r*dir(alpha+dalpha));
rr = 0.6;
draw(Label("$\mathrm{d} \alpha$",MidPoint,Relative(E)),arc(O,rr*R,alpha,alpha+dalpha),Arrow);
draw(arc(O,(r+R)/2,180-theta-1,0)--(r+R)/2*dir(0)+(0,-(R+r)/2*theta*pi/180),red+linewidth(4bp));
draw(Label("$\boldsymbol{G}_1$",EndPoint),(r+R)/2*dir(0)+(0,-(R+r)/2*theta*pi/180/2)--(r+R)/2*dir(0)+(0,-(R+r)/2*theta*pi/180/2-0.5),Arrow);
pair P;
P = (R+r)/2*dir(alpha+dalpha/2);
draw(Label("$\mathrm{d} \boldsymbol{G}$",EndPoint),P--P+(0,-0.5),Arrow);
draw(Label("$\boldsymbol{v}$",EndPoint),P--P+0.5*dir(alpha+dalpha/2-90),Arrow);
draw(Label("$\mathrm{d} \boldsymbol{N}$",EndPoint),P--P+0.5*P,Arrow);
