if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-91";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

usepackage("xeCJK");
usepackage("amsmath");
import graph;
import math;
size(300);
//惯性参考系与非惯性参考系
pair O,OO,r,i,j,k;
picture tmp;
O = (0,0);
i = 0.5*dir(-135);
j = dir(0);
k = dir(90);
draw(Label("$x$",EndPoint),O--i,Arrow);
draw(Label("$y$",EndPoint),O--j,Arrow);
draw(Label("$z$",EndPoint),O--k,Arrow);
label("$O$",O,SSE);
label("$S$",0.5*i+0.7*k);
OO = (0.7,0.5);
label(tmp,"$O'$",O,2*dir(45-25));
draw(tmp,Label("$x'$",EndPoint,S),rotate(-25)*(O--i),Arrow);
draw(tmp,Label("$y'$",EndPoint),rotate(-25)*(O--j),Arrow);
draw(tmp,Label("$z'$",EndPoint,W),rotate(-25)*(O--k),Arrow);
label(tmp,"$S'$",rotate(-25)*(0.2*j+0.7*k));
add(shift(OO)*scale(0.9)*tmp);
r = (-0.1,0.6);
dot(OO+r);
label("$P$",OO+r,N);
draw(Label("$\boldsymbol{r}_0$",Relative(0.5),Relative(E),black),O--OO,red,Arrow);
draw(Label("$\boldsymbol{r}'$",Relative(0.5),Relative(W),black),OO--OO+r,red,Arrow);
draw(Label("$\boldsymbol{r}$",Relative(0.5),Relative(W),black),O--OO+r,red,Arrow);
//draw(O--(1.7,0),invisible);
