if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-130";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
usepackage("siunitx");
import graph;
import math;
size(350);
//209页31.28
picture tmp;
pair O,i,j,k,A,B,tau,n,dirtau,dirn,ctau;
real a,h,h0,r,theta0,thetam;
path clp1,clp2;
O = (0,0);
i = (-sqrt(2)/4,-sqrt(14)/12);
j = (sqrt(14)/4,-sqrt(2)/12);
k = (0,2*sqrt(2)/3);
pair topcir(real theta){
return r*cos(theta)*i+r*sin(theta)*j+h0*k;
}
pair botcir(real theta){
return r*cos(theta)*i+r*sin(theta)*j;
}
pair helix(real theta){
return r*cos(theta)*i+r*sin(theta)*j+(a*theta)*k;
}
r = 1;
h = 3;
h0 = h;
draw(Label("$x$",EndPoint),O--2*r*i,Arrow);
draw(Label("$y$",EndPoint),O--1.5*r*j,Arrow);
draw(Label("$z$",EndPoint),O--1.2*h*k,Arrow);
clp1 = graph(botcir,0,2*pi)--cycle;
clp2 = box(r*dir(180),r*dir(0)+h*k);
unfill(clp1);
unfill(clp2);
draw(tmp,O--2*r*i,dashed);
draw(tmp,O--1.5*r*j,dashed);
draw(tmp,O--1.2*h*k,dashed);
clip(tmp,clp1);
add(tmp);
erase(tmp);
draw(tmp,O--2*r*i,dashed);
draw(tmp,O--1.5*r*j,dashed);
draw(tmp,O--1.2*h*k,dashed);
unfill(tmp,clp1);
clip(tmp,clp2);
add(tmp);
erase(tmp);
draw(graph(topcir,0,2*pi),linewidth(1bp));
theta0 = 1.9;
draw(graph(botcir,theta0,theta0+pi),dashed);
draw(graph(botcir,theta0+pi,theta0+2*pi),linewidth(1bp));
draw(r*dir(0)--r*dir(0)+h*k,linewidth(1bp));
draw(r*dir(180)--r*dir(180)+h*k,linewidth(1bp));
h0 = 1.5;
draw(graph(topcir,0,2*pi),dashed);
a = 0.208;
thetam = atan(j.x/i.x)+pi;
//draw(graph(helix,0,h/a),linewidth(1bp));
draw(graph(helix,0,thetam),linewidth(1bp));
draw(graph(helix,thetam,thetam+pi),dashed);
thetam = thetam+pi;
draw(graph(helix,thetam,thetam+pi),linewidth(1bp));
thetam = thetam+pi;
draw(graph(helix,thetam,thetam+pi),dashed);
thetam = thetam+pi;
draw(graph(helix,thetam,h/a),linewidth(1bp));
theta0 = h0/a;
A = helix(theta0);
B = h0*k;
dot(A);
label("$A$",A,SE);
label("$B$",B,W);
draw(A--B,dashed);
tau = -r*sin(theta0)*i+r*cos(theta0)*j+a*k;
n = -r*cos(theta0)*i-r*sin(theta0)*j;
dirtau = tau/(sqrt(r**2+a**2));
dirn = n/r;
ctau = -r*sin(theta0)*i+r*cos(theta0)*j;
draw(Label("$\boldsymbol{\tau}$",EndPoint),A--A+0.8*tau,Arrow);
draw(A--A+0.8*ctau,dashed);
draw(Label("$\boldsymbol{n}$",EndPoint,SSW),A--A+0.8*n,Arrow);
draw(Label("$\boldsymbol{N}$",EndPoint,ENE),A--A+0.6*dirtau+1.4*dirn,Arrow);
draw(Label("$\boldsymbol{v}$",EndPoint),A--A-0.7*tau,Arrow);
draw(A--A-h0*k--O,dashed);
draw(Label("$\boldsymbol{g}$",EndPoint,Relative(W)),A--A-0.8*k,Arrow);
r = 0.2;
draw(Label("$\beta$",MidPoint,Relative(E)),arc(A,r,degrees(0.6*dirtau+1.4*dirn),degrees(n)));
r = 0.3;
draw(arc(A,r,degrees(ctau),degrees(tau)));
draw(Label("$\alpha$",EndPoint),A+r*dir((degrees(ctau)+degrees(tau))/2)--A+r*dir((degrees(ctau)+degrees(tau))/2)+0.11*dir(-95));
//draw(A+r*dir((degrees(0.6*dirtau+1.4*dirn)+degrees(n))/2)--A+r*dir((degrees(0.6*dirtau+1.4*dirn)+degrees(n))/2)+0.11*dir(80));
draw(Label("$\phi$",MidPoint,Relative(E)),graph(botcir,0,theta0-2*pi),Arrows);
