if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-72";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
usepackage("amssymb");
size(300);
import graph;
import math;
//第六章例3惯量主轴
pair O,i,j,k;
picture tmp;
O = (0,0);
i = (-sqrt(2)/4,-sqrt(14)/12);
j = (sqrt(14)/4,-sqrt(2)/12);
k = (0,2*sqrt(2)/3);
draw(Label("$x$",EndPoint),O--1.5*i,Arrow);
draw(Label("$y$",EndPoint),O--1.5*j,Arrow);
draw(Label("$z$",EndPoint),O--1.5*k,Arrow);
label("$O$",O,W);
path clp;
clp = i--i+j--j--j+k--k--i+k--cycle;
unfill(clp);
draw(tmp,Label("$x$",EndPoint),O--1.5*i,dashed,Arrow);
draw(tmp,Label("$y$",EndPoint),O--1.5*j,dashed,Arrow);
draw(tmp,Label("$z$",EndPoint),O--1.5*k,dashed,Arrow);
label(tmp,"$O$",O,W);
clip(tmp,clp);
add(tmp);
erase(tmp);
draw(clp);
draw(i+k--i+j+k--j+k);
draw(i+j--i+j+k);
draw(-i--(-i+k),dashed);
draw(-i--(j-i),dashed);
draw(i--(i-2*k)--(i+j-2*k)--(j-2*k)--j,dashed);
draw(O--(-2*k)--(j-2*k),dashed);
draw((-2*k)--(i-2*k),dashed);
draw(i+j--(i+j-2*k),dashed);
draw(j--(j-i)--(j-i+k)--j+k,dashed);
draw(k--(k-i)--(k-i+j),dashed);
draw(O--(i+j-2*k),dashed);
draw(O--(j-i),dashed);
draw(O--i+j+k,dashed);
draw(Label("$x'$",EndPoint,Relative(E),black),O--(i+j-2*k)/sqrt(3),red,Arrow);
draw(Label("$y'$",EndPoint,black),O--(-i+j),red,Arrow);
draw(Label("$z'$",EndPoint,N,black),O--(i+j+k),red,Arrow);
//draw(O--(1.7,0),invisible);
