if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-90";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(400);
//直立转动Lagrange陀螺的等效势能曲线
picture tmp;
pair O,P;
real alpha,beta,top,bot,x,left,right,height;
path clp;
real U(real theta){
return 10*(beta*(cos(alpha/2))**2*(sec(theta/2))**2+cos(theta));
}
O = (0,0);
alpha = 1.3;
beta = 0;
top = 70;
bot = U(pi);
x = 20;
draw(tmp,O--(pi,0));
draw(tmp,(alpha,bot)--(alpha,top),dashed);
beta = 0;
draw(tmp,graph(U,0,pi),black+linewidth(1bp));
draw(tmp,Label("$E_1$",BeginPoint),(0,U(alpha))--(pi,U(alpha)),black);
beta = (cos(alpha/2))**2;
draw(tmp,graph(U,0,3),red+linewidth(1bp));
draw(tmp,Label("$E_2$",BeginPoint),(0,U(alpha))--(pi,U(alpha)),red);
beta = 2*(cos(alpha/2))**2;
draw(tmp,graph(U,0,3),orange+linewidth(1bp));
draw(tmp,Label("$E_3$",BeginPoint),(0,U(alpha))--(pi,U(alpha)),orange);
beta = (2*(cos(alpha/2))**2+2)/2;
draw(tmp,graph(U,0,3),green+linewidth(1bp));
draw(tmp,Label("$E_4$",BeginPoint),(0,U(alpha))--(pi,U(alpha)),green);
beta = 2;
draw(tmp,graph(U,0,3),blue+linewidth(1bp));
draw(tmp,Label("$E_5$",BeginPoint),(0,U(alpha))--(pi,U(alpha)),blue);
beta = (2+2*(sec(alpha/2))**2)/2;
draw(tmp,graph(U,0,3),darkblue+linewidth(1bp));
draw(tmp,Label("$E_6$",BeginPoint),(0,U(alpha))--(pi,U(alpha)),darkblue);
beta = 2*(sec(alpha/2))**2;
draw(tmp,graph(U,0,3),purple+linewidth(1bp));
draw(tmp,Label("$E_7$",BeginPoint),(0,U(alpha))--(pi,U(alpha)),purple);
beta = 3*(sec(alpha/2))**2;
draw(tmp,graph(U,0,3),brown+linewidth(1bp));
draw(tmp,Label("$E_8$",BeginPoint),(0,U(alpha))--(pi,U(alpha)),brown);
clp = box((-10,bot),(pi,top));
clip(tmp,clp);
clp = box((0,bot),(pi,top));
draw(tmp,clp);
top = 60;
clp = box((-1,bot),(pi,top));
clip(tmp,clp);
add(xscale(x)*tmp);
label("$0$",(0,bot),S);
label("$\pi$",(x*pi,bot),S);
label("$\alpha$",(x*alpha,bot),S);
label("$\theta$",(x*pi,bot),E);
label("$U$",(0,top),N);
label("$0$",O,W);
left = x*pi+4;
right = x*pi+30;
height = 66;
top = top-2;
fill(shift((1,-1))*box((left,top),(right,top-height)),black);
unfill(box((left,top),(right,top-height)));
draw(box((left,top),(right,top-height)));
P = ((left+right)/2,top-height+height/16);
label("$\dfrac{r\omega^2}{g} = 0$",P,black);
P = ((left+right)/2,top-height+3*height/16);
label("$0 < \dfrac{r\omega^2}{g} < 2\cos^2 \dfrac{\alpha}{2}$",P,red);
P = ((left+right)/2,top-height+5*height/16);
label("$\dfrac{r\omega^2}{g} = 2\cos^2 \dfrac{\alpha}{2}$",P,orange);
P = ((left+right)/2,top-height+7*height/16);
label("$2\cos^2 \dfrac{\alpha}{2} < \dfrac{r\omega^2}{g} < 2$",P,green);
P = ((left+right)/2,top-height+9*height/16);
label("$\dfrac{r\omega^2}{g} = 2$",P,blue);
P = ((left+right)/2,top-height+11*height/16);
label("$2 < \dfrac{r\omega^2}{g} < 2\sec^2 \dfrac{\alpha}{2}$",P,darkblue);
P = ((left+right)/2,top-height+13*height/16);
label("$\dfrac{r\omega^2}{g} = 2\sec^2 \dfrac{\alpha}{2}$",P,purple);
P = ((left+right)/2,top-height+15*height/16);
label("$\dfrac{r\omega^2}{g} > 2\sec^2 \dfrac{\alpha}{2}$",P,brown);
//draw(O--(right*1.05,0),invisible);
