if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-57";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(300);
//弹性耦合摆
pair O1,O2;
real theta1,theta2,d,l,r;
O1 = (0,0);
l = 1;
d = 0.8;
O2 = (d,0);
theta1 = 25;
theta2 = 35;
draw(O1--O1+0.6*l*dir(-90),dashed);
draw(O2--O2+0.6*l*dir(-90),dashed);
draw(Label("$l$",MidPoint,Relative(W)),O1--O1+l*dir(theta1-90));
draw(Label("$l$",MidPoint,Relative(W)),O2--O2+l*dir(theta2-90));
r = 0.03;
fill(shift(O1+l*dir(theta1-90))*scale(r)*unitcircle,black);
label("$m$",O1+l*dir(theta1-90),2*W);
fill(shift(O2+l*dir(theta2-90))*scale(r)*unitcircle,black);
label("$m$",O2+l*dir(theta2-90),2*E);
r = 0.1;
draw(Label("$\theta_1$",MidPoint,Relative(E)),arc(O1,r,-90,theta1-90),Arrow);
draw(Label("$\theta_2$",MidPoint,Relative(E)),arc(O2,r,-90,theta2-90),Arrow);
draw(Label("$d$",MidPoint,Relative(E)),O1+0.3*l*dir(180)--O2+0.3*l*dir(0),linewidth(1bp));
draw(shift(O1+l*dir(theta1-90))*rotate(degrees(O2+l*dir(theta2-90)-O1-l*dir(theta1-90)))*scale(abs(O2+l*dir(theta2-90)-O1-l*dir(theta1-90))/10/pi)*graph(sin,0,10*pi));
label("$k$",interp(O1+l*dir(theta1-90),O2+l*dir(theta2-90),0.5),2*S);
//draw(O1--O2--O2+l*dir(theta2-90)+(0.2,0),invisible);
