if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-31";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(200);
//第三章例7图
pair O;
real R,r,theta;
R = 3;
theta = 60;
r = 0.15;
O = (0,0);
draw(arc(O,R,0,180)--cycle);
draw(Label("$R$",MidPoint,W),O--R*dir(90),dashed);
draw(O--R*dir(theta),dashed);
draw(Label("$\theta$",MidPoint,Relative(W)),arc(O,0.6,90,theta),Arrow);
fill(shift((R+r)*dir(theta))*scale(r)*unitcircle,black);
label("$m$",(R+r)*dir(theta),3*E);
draw(Label("$\boldsymbol{N}$",EndPoint),(R+r)*dir(theta)--(R+r)*dir(theta)+dir(theta),Arrow);
