if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-19";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
import graph;
import math;
size(200);
//约束在曲面上的质点
pair A[],O,a,b,ns,g1,g2;
O = (0,0);
a = (2,0);
b = (0.5,1);
A[1] = O-a-b;
A[2] = O+a-b;
A[3] = O+a+b;
A[4] = O-a+b;
A[5] = (A[1]+A[2])/2+(0,0.3);
A[6] = (A[2]+A[3])/2+(0,0.2);
A[7] = (A[3]+A[4])/2+(0,0.3);
A[8] = (A[4]+A[1])/2+(0,0.2);
path surf,row,col;
surf = A[1]..A[5]..A[2]--A[2]..A[6]..A[3]--A[3]..A[7]..A[4]--A[4]..A[8]..A[1]--cycle;
ns = (A[5]+A[7])/2+(0,0.2);
col = A[5]..ns..A[7];
row = A[6]..ns..A[8];
draw(surf);
draw(row,dashed);
draw(col,dashed);
g1 = 1*dir(row,1);
g2 = 0.6*dir(col,1);
draw(ns-g1-g2--ns+g1-g2--ns+g1+g2--ns-g1+g2--cycle);
draw(Label("$\boldsymbol{n}$",EndPoint),ns--ns+0.8*dir(90),Arrow);
draw(Label("$\delta\boldsymbol{r}$",EndPoint),ns--ns+0.5*dir(30),red,Arrow);
//draw(O--A[3]+(0.4,0),invisible);
