if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="CM_chs-128";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

texpreamble("\usepackage{xeCJK}");
texpreamble("\setCJKmainfont{SimSun}");
usepackage("amsmath");
usepackage("siunitx");
import graph;
import math;
size(250);
//102页14.13
picture dashpic;
pair O,A,C,dash,P;
real phi,theta,a,r,l,ll,tri,ri,ro,d;
path tre;
O = (0,0);
phi = 60;
a = 1;
r = 1.4;
l = 2.2;
ll = 0.7*l;
d = 0.07;
tri = 0.3;
ri = 0.05;
ro = 0.1;
dash = dir(-135);
tre = a*dir(180)--a*dir(0);
draw(dashpic,tre,linewidth(1bp));
for(real r=0;r<=1;r=r+0.04){
P = relpoint(tre,r);
draw(dashpic,P--P+dash);
}
C = a*dir(90-phi);
draw(Label("$x$",EndPoint),O--(2*a+l)*dir(90),dashed);
draw(Label("$a$",MidPoint,Relative(E)),O--C);
draw(shift(C)*scale(r)*unitcircle,linewidth(0.8bp));
draw(O--tri*dir(-60)--tri*dir(-120)--cycle,linewidth(0.8bp));
clip(dashpic,box((-tri,-1.6*d),(tri,1)));
add(shift(tri*Sin(60)*dir(-90))*dashpic);
theta = aSin(a/(r+ro)*Sin(phi));
A = C+(r+ro)*dir(theta+90);
draw(Label("$r$",MidPoint,Relative(W)),A--C,dashed);
draw(shift(A)*box((-d,0),(d,l)),linewidth(0.8bp));
unfill(shift(A)*scale(ro)*unitcircle);
draw(shift(A)*scale(ro)*unitcircle,linewidth(0.8bp));
draw(shift(A)*scale(ri)*unitcircle,linewidth(0.8bp));
unfill(shift(C)*scale(ro)*unitcircle);
draw(shift(C)*scale(ro)*unitcircle,linewidth(0.8bp));
draw(shift(C)*scale(ri)*unitcircle,linewidth(0.8bp));
unfill(shift(O)*scale(ro)*unitcircle);
draw(shift(O)*scale(ro)*unitcircle,linewidth(0.8bp));
draw(shift(O)*scale(ri)*unitcircle,linewidth(0.8bp));
tri = 0.7*tri;
clip(dashpic,box((-tri,-1.6*d),(tri,1)));
draw(dashpic,(-tri,0)--(-tri,-1.6*d),linewidth(1bp));
draw(dashpic,(tri,0)--(tri,-1.6*d),linewidth(1bp));
add(shift(A+ll*dir(90)+1.5*d*dir(0))*rotate(90)*dashpic);
add(shift(A+ll*dir(90)+1.5*d*dir(180))*rotate(-90)*dashpic);
label("$O$",O,2*W);
label("$C$",C,2*E);
label("$A$",A,2*W);
r = 0.4;
draw(Label("$\phi$",MidPoint,Relative(E)),arc(O,r,90-phi,90),Arrows);
